### ISSUE TITLE
config.service not found on raspbian

### ISSUE THREAD

**Issue by pavel-shvagirev** [sous-chefs/nfs#118]
Service 'config' (config.service) can not be found on Raspbian and therefore started, causing whole setup to constantly fail on that OS. The reason is that Rasbian has that service called nfs-config (like Ubuntu does). But Raspbian does not match a default['nfs']['service']['config'] check because its 'platform' attribute is not 'debian', but 'raspbian' (platform_family is 'debian' instead).

As a workaround, attributes/default.rb sould be modified somehow, for example:

```
--- a/chef-repo/cookbooks/nfs/attributes/default.rb
+++ b/chef-repo/cookbooks/nfs/attributes/default.rb
@@ -47,6 +47,8 @@ default['nfs']['packages'] = if node['platform_family'] == 'debian'
 default['nfs']['service']['config'] = if (node['platform'] == 'debian' && node['platform_version'].to_i >= 10) ||
                                          (node['platform'] == 'ubuntu' && node['platform_version'].to_i >= 15)
                                         'nfs-config.service'
+                                      else
+                                        'nfs-config.service'
                                       end
```

**Comment by pavel-shvagirev** [comment]
On v4.0.0:
  47   │ default['nfs']['service']['config'] = 'nfs-config.service' if platform?('debian', 'ubuntu')
should be 
  47   │ default['nfs']['service']['config'] = 'nfs-config.service' if platform?('debian', 'ubuntu', 'raspbian')

**Comment by ramereth** [comment]
@pavel-shvagirev we can certainly do that! We're going to work on getting this cookbook properly imported into Sous Chefs first and cleaned up a little. I'll try and make sure this gets included in that release.

**Comment by damacus** [comment]
Platform family will probably work better here then

**Comment by pavel-shvagirev** [comment]
> Platform family will probably work better here then

Agreed. platform_family for Raspbian is debian

**Comment by damacus** [comment]
@pavel-shvagirev do you fancy making a PR for this change. Happy to ship it 👍🏼
