### ISSUE TITLE
Metadata incorrect for 5.0.5

### ISSUE THREAD

**Issue by dreambeyondorange** [sous-chefs/nfs#138]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Metadata lists 5.0.4 as the version in the 5.0.5 tag https://github.com/sous-chefs/nfs/blob/5.0.5/metadata.rb

## :pancakes: Cookbook version

5.0.5

**Comment by ramereth** [comment]
@dreambeyondorange looks like we had some issues with the release system and those releases didn't get properly tagged released. I'll see if we can fix those.
